import = [
    # "~/dotfiles/.config/alacritty/themes/themes/citylights.toml"   
    # "~/dotfiles/.config/alacritty/themes/themes/carbonfox.toml" 
     "~/dotfiles/.config/alacritty/themes/themes/catppuccin_mocha.toml" 
]

[font]
#normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
normal = { family = "SF Mono", style = "Regular"}
size = 13

[window]
decorations = "None"
opacity = 0.97
dimensions = { columns = 150, lines = 40}
[env]
TERM = "xterm-256color"


