#general.import = [
    # "~/dotfiles/.config/alacritty/themes/themes/citylights.toml"   
    # "~/dotfiles/.config/alacritty/themes/themes/carbonfox.toml" 
#     "~/dotfiles/.config/alacritty/themes/themes/catppuccin_mocha.toml" 
#]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light"}
#normal = { family = "SF Mono", style = "Regular"}
#normal = { family = "Fira Code", style = "Regular"}
#normal = { family = "Consolas", style = "Regular"}
size = 14

[window]
decorations = "None"
opacity = 0.97
dimensions = { columns = 150, lines = 40}
blur = true
[env]
TERM = "xterm-256color"


